import "package:firebase_core/firebase_core.dart";
import "package:flutter/foundation.dart";

import "../../config/app_config.dart";

/// Initializes Firebase without committing generated provider files.
///
/// Web receives its public Firebase configuration through dart-defines. Native
/// targets intentionally use their platform files generated by FlutterFire
/// (`google-services.json`, `GoogleService-Info.plist`, etc.) when the team has
/// access to the Firebase project.
class FirebaseBootstrapService {
  const FirebaseBootstrapService();

  static Future<void>? _initialization;

  bool get isConfigured => AppConfig.firebaseConfigured;

  Future<void> ensureInitialized() async {
    if (!isConfigured) {
      throw StateError(
        "Firebase n'est pas configuré. Fournis FIREBASE_API_KEY, FIREBASE_APP_ID, "
        "FIREBASE_MESSAGING_SENDER_ID et FIREBASE_PROJECT_ID via --dart-define.",
      );
    }
    _initialization ??= _initializeInternal();
    await _initialization;
  }

  Future<void> _initializeInternal() async {
    if (Firebase.apps.isNotEmpty) return;

    if (!kIsWeb) {
      await Firebase.initializeApp();
      return;
    }

    await Firebase.initializeApp(
      options: FirebaseOptions(
        apiKey: AppConfig.firebaseApiKey,
        appId: AppConfig.firebaseAppId,
        messagingSenderId: AppConfig.firebaseMessagingSenderId,
        projectId: AppConfig.firebaseProjectId,
        authDomain: _emptyToNull(AppConfig.firebaseAuthDomain),
        storageBucket: _emptyToNull(AppConfig.firebaseStorageBucket),
        measurementId: _emptyToNull(AppConfig.firebaseMeasurementId),
      ),
    );
  }

  String? _emptyToNull(String value) {
    final trimmed = value.trim();
    return trimmed.isEmpty ? null : trimmed;
  }
}
